# Generated by Django 3.0.5 on 2021-06-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
